DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(
  ID BIGINT IDENTITY PRIMARY KEY,
  ISBN VARCHAR(128) NOT NULL UNIQUE,
  AUTHOR VARCHAR(128) NOT NULL,
  TITLE VARCHAR(128) NOT NULL,
  TAGS VARCHAR(128) NOT NULL
);